### ISSUE TITLE
can not install on redmine 3.2.1

### ISSUE THREAD

**Issue by archonwang** [Restream/redmine_customize#8]
I tried to install it on redmine 3.2.x, but Unfortunately , I have not succeeded in it. Need help so much.
How to solve it? Thanks in advance.

[root@redmine]# bundle exec rake redmine:plugins:migrate  RAILS_ENV=production

> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
> /opt/redmine/plugins/redmine_issue_checklist/init.rb:24: warning: duplicated key at line 24 ignored: :issue_checklist
> rake aborted!
> Unknown key: :order. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/core_ext/hash/keys.rb:75:in `block in assert_valid_keys'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/core_ext/hash/keys.rb:73:in`each_key'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/core_ext/hash/keys.rb:73:in `assert_valid_keys'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:82:in`validate_options'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:62:in `initialize'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/collection_association.rb:18:in`initialize'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:47:in `new'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:47:in`create_builder'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:35:in `build'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/associations.rb:1259:in`has_many'
> /opt/redmine/plugins/redmine_customize/lib/redmine_customize/patches/user_patch.rb:9:in `block in <module:UserPatch>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/concern.rb:120:in`class_eval'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/concern.rb:120:in `append_features'
> /opt/redmine/plugins/redmine_customize/lib/redmine_customize/patches/user_patch.rb:41:in`include'
> /opt/redmine/plugins/redmine_customize/lib/redmine_customize/patches/user_patch.rb:41:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`block in require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`require'
> /opt/redmine/plugins/redmine_customize/lib/redmine_customize.rb:10:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`block in require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`require'
> /opt/redmine/plugins/redmine_customize/init.rb:7:in `block in <top (required)>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in`instance_exec'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in`call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in`call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in`each'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in`**run_callbacks**'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in`run_callbacks'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in`prepare!'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in`instance_exec'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in`block in run_initializers'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application.rb:352:in`initialize!'
> /opt/redmine/config/environment.rb:14:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`block in require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`require'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require_environment!'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application.rb:457:in`block in run_tasks_blocks'
> Tasks: TOP => redmine:plugins:migrate => environment
> (See full trace by running task with --trace)

**Comment by archonwang** [comment]
OK, I reinstall a new Redmine 3.2.X and to install the plugin and still with conflict as follows:

> Resolving dependencies....
> Bundler could not find compatible versions for gem "nokogiri":
>   In snapshot (Gemfile.lock):
>     nokogiri (= 1.6.7.2)
> 
>   In Gemfile:
>     nokogiri (>= 1.6.7.2)
> 
>     capybara was resolved to 2.6.2, which depends on
>       nokogiri (>= 1.3.3)
> 
>     deface (< 1.0.0) was resolved to 0.1.0, which depends on
>       nokogiri (~> 1.4.3)
> 
>     rails-html-sanitizer (>= 1.0.3) was resolved to 1.0.3, which depends on
>       loofah (~> 2.0) was resolved to 2.0.3, which depends on
>         nokogiri (>= 1.5.9)
> 
>     rails-dom-testing was resolved to 1.0.7, which depends on
>       nokogiri (~> 1.6.0)
> 
>     roadie-rails was resolved to 1.1.1, which depends on
>       roadie (~> 3.1) was resolved to 3.1.1, which depends on
>         nokogiri (< 1.7.0, >= 1.5.0)
> 
>     capybara was resolved to 2.6.2, which depends on
>       xpath (~> 2.0) was resolved to 2.0.0, which depends on
>         nokogiri (~> 1.3)
> 
> Running `bundle update` will rebuild your snapshot from scratch, using only
> the gems in your Gemfile, which may resolve the conflict.

I used <bundle update> try to resolve the conflict, and error again as follow

> Resolving dependencies.............
> Bundler could not find compatible versions for gem "nokogiri":
>   In Gemfile:
>     nokogiri (>= 1.6.7.2)
> 
>     deface (< 1.0.0) was resolved to 0.5.2, which depends on
>       nokogiri (~> 1.4.3)
> 
>     rails-html-sanitizer (>= 1.0.3) was resolved to 1.0.3, which depends on
>       loofah (~> 2.0) was resolved to 2.0.3, which depends on
>         nokogiri (>= 1.5.9)
> Bundler could not find compatible versions for gem "rails":
>   In Gemfile:
>     rails (= 4.2.5.2)
> 
>     deface (< 1.0.0) was resolved to 0.1.0, which depends on
>       rails (~> 3.0.0)

could you fix it, Thanks so much.

**Comment by bbszabi** [comment]
Well, I'm having the same issue with impossible Nokogiri version requirements. Essentially, deface wants version 1.4.3, whil eother components depend on other (higher) Nokogiri versions. Im not a ruby guy, so I have no idea if this can be fixed and if yes, how?

**Comment by archonwang** [comment]
try the recently version of this plugins, it removed the Gemfile.lock maybe solve the problem.
