### ISSUE TITLE
domain.com/issues/new -- Internal error

### ISSUE THREAD

**Issue by juxta73** [Restream/redmine_customize#9]
500 error when try to create a task on the link (domain.com/issues/new) 

--log --

Started GET "/issues/new" for 87.76.11.73 at 2017-01-19 01:17:40 +0400
Processing by IssuesController#new as HTML
  Current user: Eric (id=7)
  Rendered issues/_form_custom_fields.html.erb (2.8ms)
  Rendered issues/_attributes.html.erb (12.1ms)
  Rendered plugins/redmine_customize/app/views/customize/_issues_form_details_bottom.html.erb (0.2ms)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist_form.html.erb (0.2ms)
  Rendered issues/_form.html.erb (25.2ms)
  Rendered attachments/_form.html.erb (1.6ms)
[1;32mDeface: [WARNING][0m No :original defined for 'get_url_link', you should change its definition to include:
 :original => '7340a575d6685b3585e9a5cbb933caee5bb5a8bb' 
  Rendered issues/new.html.erb within layouts/base (43.2ms)
Completed 500 Internal Server Error in 64ms (ActiveRecord: 12.1ms)

ActionView::Template::Error (undefined method `identifier' for nil:NilClass):
    49: 
    50:   <%= submit_tag l(:button_create) %>
    51:   <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
    52:   <%= preview_link preview_new_issue_path(:project_id => @issue.project), 'issue-form' %><%= link_to l(:label_get_url), '#', id: 'get-url-link', class: 'icon custom-icon-table_link', data: { url: project_draft_issues_url(@project.identifier, only_path: false) } %>
    53: <% end %>
    54: 
    55: <div id="preview" class="wiki"></div>
  app/views/issues/new.html.erb:52:in `block in _5884f8b6c81ff6a80ff4f306eb9af75d'
  app/helpers/application_helper.rb:1051:in `labelled_form_for'
  app/views/issues/new.html.erb:5:in `_5884f8b6c81ff6a80ff4f306eb9af75d'
  app/controllers/issues_controller.rb:129:in `block (2 levels) in new'
  app/controllers/issues_controller.rb:128:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
00

**Comment by juxta73** [comment]
problem in  'overrides/issues/new.rb'

deleting this file resolve 500 error when you create a task from the page http://domain/issues

ps. sorry my bad english

**Comment by nodecarter** [comment]
Hi @juxta73 , which redmine version do you use?

**Comment by juxta73** [comment]
Hi @nodecarter ,

Environment:
  Redmine version                3.3.1.stable.16111
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  periodictask                   3.1.1
  redmine__select2               1.1.0
  redmine_banner                 0.1.2
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.4
  redmine_customize              1.2.2
  redmine_lightbox2              0.3.1
  sidebar_hide                   0.0.8
